import type { UsageProviderMeta } from "./types.js";

export const USAGE_PROVIDERS: UsageProviderMeta[] = [
  {
    toolId: "claude",
    label: "Claude Code",
    supported: true,
    docsUrl: "https://platform.claude.com/docs/en/manage-claude/usage-cost-api",
    credentialNoteKey: "usage.claude.intro",
    fields: [
      {
        key: "adminApiKey",
        label: "Admin API key",
        labelKey: "usage.claude.auth.team.field",
        groupKey: "team",
        groupLabelKey: "usage.claude.auth.team.title",
        noteKey: "usage.claude.auth.team.note",
        placeholder: "sk-ant-admin01-…",
        helpUrl: "https://platform.claude.com/docs/en/api/administration-api",
      },
      {
        key: "sessionKey",
        label: "Session cookie",
        labelKey: "usage.claude.auth.personal.sessionField",
        groupKey: "personal",
        groupLabelKey: "usage.claude.auth.personal.title",
        noteKey: "usage.claude.auth.personal.note",
        placeholder: "sk-ant-sid02-… or full cookie string",
        helpUrl: "https://claude.ai/settings/usage",
        helpLinkKey: "usage.claude.auth.personal.openUsage",
      },
      {
        key: "cfClearance",
        label: "Cloudflare clearance",
        labelKey: "usage.claude.auth.personal.cfField",
        groupKey: "personal",
        placeholder: "cf_clearance value (required for most users)",
        helpUrl: "https://claude.ai",
        helpLinkKey: "usage.claude.auth.personal.openUsage",
      },
      {
        key: "orgId",
        label: "Organization ID",
        labelKey: "usage.claude.auth.personal.orgField",
        groupKey: "personal",
        placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (optional)",
        helpUrl: "https://claude.ai/settings/account",
        helpLinkKey: "usage.claude.auth.personal.openAccount",
      },
    ],
  },
  {
    toolId: "codex",
    label: "OpenAI Codex",
    supported: true,
    docsUrl: "https://developers.openai.com/api/docs/guides/admin-apis",
    fields: [
      {
        key: "adminApiKey",
        label: "Admin API key",
        placeholder: "sk-admin-…",
        helpUrl: "https://platform.openai.com/settings/organization/admin-keys",
      },
    ],
  },
  {
    toolId: "cursor",
    label: "Cursor",
    supported: true,
    docsUrl: "https://cursor.com/docs/account/teams/admin-api",
    credentialNoteKey: "usage.cursor.intro",
    fields: [
      {
        key: "adminApiKey",
        label: "Admin API key",
        labelKey: "usage.cursor.auth.team.field",
        groupKey: "team",
        groupLabelKey: "usage.cursor.auth.team.title",
        noteKey: "usage.cursor.auth.team.note",
        placeholder: "key_…",
        helpUrl: "https://cursor.com/docs/api",
      },
      {
        key: "sessionToken",
        label: "Dashboard session cookie",
        labelKey: "usage.cursor.auth.personal.field",
        groupKey: "personal",
        groupLabelKey: "usage.cursor.auth.personal.title",
        noteKey: "usage.cursor.auth.personal.note",
        placeholder: "user_…::eyJ…",
        helpUrl: "https://cursor.com/dashboard/usage",
        helpLinkKey: "usage.cursor.auth.personal.openDashboard",
      },
    ],
  },
  {
    toolId: "gemini",
    label: "Google Gemini CLI",
    supported: true,
    docsUrl: "https://ai.google.dev/gemini-api/docs/billing",
    credentialNoteKey: "usage.gemini.intro",
    fields: [
      {
        key: "apiKey",
        label: "API key",
        labelKey: "usage.gemini.auth.apiKey.field",
        groupKey: "apiKey",
        groupLabelKey: "usage.gemini.auth.apiKey.title",
        noteKey: "usage.gemini.auth.apiKey.note",
        placeholder: "AIza…",
        helpUrl: "https://aistudio.google.com/apikey",
      },
      {
        key: "serviceAccountJson",
        label: "GCP service account JSON",
        labelKey: "usage.gemini.auth.gcp.field",
        groupKey: "gcp",
        groupLabelKey: "usage.gemini.auth.gcp.title",
        noteKey: "usage.gemini.auth.gcp.note",
        placeholder: "{ \"type\": \"service_account\", … }",
        helpUrl: "https://cloud.google.com/iam/docs/service-accounts-create",
      },
      {
        key: "projectId",
        label: "GCP project ID",
        labelKey: "usage.gemini.auth.gcp.projectField",
        groupKey: "gcp",
        placeholder: "my-gemini-project (optional)",
        helpUrl: "https://console.cloud.google.com/iam-admin/serviceaccounts",
      },
    ],
  },
  {
    toolId: "copilot",
    label: "GitHub Copilot CLI",
    supported: true,
    docsUrl: "https://docs.github.com/en/rest/copilot/copilot-usage-metrics",
    credentialNoteKey: "usage.copilot.intro",
    fields: [
      {
        key: "pat",
        label: "Personal access token",
        labelKey: "usage.copilot.auth.pat.field",
        groupKey: "auth",
        groupLabelKey: "usage.copilot.auth.pat.title",
        noteKey: "usage.copilot.auth.pat.note",
        placeholder: "ghp_… or github_pat_…",
        helpUrl: "https://github.com/settings/tokens",
      },
      {
        key: "org",
        label: "Organization",
        labelKey: "usage.copilot.auth.org.field",
        groupKey: "scope",
        groupLabelKey: "usage.copilot.auth.org.title",
        noteKey: "usage.copilot.auth.org.note",
        placeholder: "my-org (optional)",
        helpUrl: "https://docs.github.com/en/copilot/reference/copilot-usage-metrics/copilot-usage-metrics",
      },
      {
        key: "enterprise",
        label: "Enterprise slug",
        labelKey: "usage.copilot.auth.enterprise.field",
        groupKey: "scope",
        groupLabelKey: "usage.copilot.auth.enterprise.title",
        noteKey: "usage.copilot.auth.enterprise.note",
        placeholder: "my-enterprise (optional)",
        helpUrl: "https://docs.github.com/en/enterprise-cloud@latest/rest/copilot/copilot-usage-metrics",
      },
    ],
  },
];

export function getUsageProvider(toolId: string): UsageProviderMeta | undefined {
  return USAGE_PROVIDERS.find((p) => p.toolId === toolId);
}
