/**
 * Record the CJK input path of one terminal into the shared trace buffer.
 *
 * Deliberately separate from `./xterm-ime-anchor`: the anchor owns the IME's
 * *position* and rewrites styles, while this only observes. Keeping them apart
 * means the trace can stay attached — and keep explaining dropped input —
 * without any risk of perturbing the thing it is watching.
 *
 * Listeners go on the terminal element in the capture phase, not on the
 * textarea. A capture listener on the *target* buys nothing: target-phase
 * listeners run in registration order, and xterm registers its own inside
 * `term.open()`, which is before this module attaches. Ordering matters most
 * for `blur`, where xterm's `_handleTextAreaBlur` empties `textarea.value`
 * before returning — recorded after it, every blur would show an empty
 * textarea and quietly mislead whoever reads the dump.
 */

import type { Terminal } from "@xterm/xterm";
import { recordImeInput } from "./ime-input-log";

export function attachImeInputTrace(terminal: Terminal, sessionId: string): () => void {
  const root = terminal.element;
  if (!root) return () => {};

  const textarea = root.querySelector(".xterm-helper-textarea") as HTMLTextAreaElement | null;
  if (!textarea) return () => {};

  /** The pane holds other focusable nodes (find bar); only the IME path counts. */
  const fromTextarea = (ev: Event): boolean => ev.target === textarea;

  const onFocus = (ev: Event) => {
    if (!fromTextarea(ev)) return;
    recordImeInput({ sessionId, kind: "focus", textareaValue: textarea.value });
  };
  const onBlur = (ev: Event) => {
    if (!fromTextarea(ev)) return;
    recordImeInput({ sessionId, kind: "blur", textareaValue: textarea.value });
  };

  const composition =
    (kind: "composition-start" | "composition-update" | "composition-end") => (ev: Event) => {
      if (!fromTextarea(ev)) return;
      recordImeInput({
        sessionId,
        kind,
        data: (ev as CompositionEvent).data ?? "",
        trusted: ev.isTrusted,
        textareaValue: textarea.value,
      });
    };
  const onCompositionStart = composition("composition-start");
  const onCompositionUpdate = composition("composition-update");
  const onCompositionEnd = composition("composition-end");

  const onKeyDown = (ev: Event) => {
    if (!fromTextarea(ev)) return;
    const k = ev as KeyboardEvent;
    recordImeInput({
      sessionId,
      kind: "keydown",
      key: k.key,
      // 229 is Chromium's "Process" code for a key the IME owns; xterm's
      // CompositionHelper.keydown returns early on it.
      keyCode: k.keyCode,
      isComposing: k.isComposing,
      trusted: ev.isTrusted,
      textareaValue: textarea.value,
    });
  };

  const onWindowFocus = () => recordImeInput({ sessionId, kind: "window-focus" });
  const onWindowBlur = () => recordImeInput({ sessionId, kind: "window-blur" });

  root.addEventListener("focus", onFocus, true);
  root.addEventListener("blur", onBlur, true);
  root.addEventListener("compositionstart", onCompositionStart, true);
  root.addEventListener("compositionupdate", onCompositionUpdate, true);
  root.addEventListener("compositionend", onCompositionEnd, true);
  root.addEventListener("keydown", onKeyDown, true);
  window.addEventListener("focus", onWindowFocus);
  window.addEventListener("blur", onWindowBlur);

  return () => {
    root.removeEventListener("focus", onFocus, true);
    root.removeEventListener("blur", onBlur, true);
    root.removeEventListener("compositionstart", onCompositionStart, true);
    root.removeEventListener("compositionupdate", onCompositionUpdate, true);
    root.removeEventListener("compositionend", onCompositionEnd, true);
    root.removeEventListener("keydown", onKeyDown, true);
    window.removeEventListener("focus", onWindowFocus);
    window.removeEventListener("blur", onWindowBlur);
  };
}

/**
 * Traffic on `onData` the terminal generated by itself rather than from a
 * keystroke, and which would evict the evidence from a 400-entry ring:
 *
 * - mouse reports, SGR and legacy X10, one per pointer move in tracking mode
 * - cursor-position reports (`ESC [ row ; col R`)
 * - primary / secondary device attributes (`ESC [ ? … c`)
 * - OSC and DCS replies to colour and keyboard-protocol queries
 *
 * Ink-based CLIs issue the queries behind those replies on every redraw, so
 * without this a second of hovering the pane buries the composition.
 * Deliberately narrow: `ESC [ A` and friends are real user input and stay.
 */
const SELF_REPORT =
  /^(?:\x1b\[<\d+;\d+;\d+[Mm]|\x1b\[M[\s\S]{3}|\x1b\[\d+;\d+R|\x1b\[\?[\d;]*c|\x1b\][\s\S]*?(?:\x07|\x1b\\)|\x1bP[\s\S]*?\x1b\\)$/;

/** Bytes xterm handed to the PTY — the far end of the path this trace covers. */
export function recordImeInputData(sessionId: string, data: string): void {
  if (SELF_REPORT.test(data)) return;
  recordImeInput({ sessionId, kind: "data", data });
}
